version: "3"
services:
  db:
    container_name: db_mysql
    build: ./mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      is_app:
        ipv4_address: 172.30.0.5

  server:
    container_name: server_express
    build: ./server/
    ports:
      - "5000:5000"
    environment:
      DB_HOST: 172.30.0.5
    networks:
      is_app:
        ipv4_address: 172.30.0.10
    depends_on:
      - db

  client:
    container_name: client_react
    build: ./client
    ports:
      - "80:80"
    networks:
      is_app:
        ipv4_address: 172.30.0.15
    depends_on:
      - db

networks:
  is_app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
volumes:
  db_data:
